name: Build-Release

on:
  release:
    types: [created]

env:
  SEMVER: ${{ github.event.release.tag_name }}

jobs:
  
  Test:
    name: get semver
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: get tag
      run: |
        echo $SEMVER
        case ${GITHUB_REF} in 
          refs/heads/test)
            echo "It's build from tag on Test branch";;
          refs/heads/main)
            echo "It's build from tag on main branch";;
          *)
            echo "It's build from tag on Other branch";;
          
        esac
        MODIFIED=$(date "+%Y-%m-%dT%H:%MZ")
        echo "::set-output name=MODIFIED::${MODIFIED}"
        
    
