name: Build-Release

on:
  release:
    types: [created]

env:
  SEMVER: ${{ github.event.release.tag_name }}

jobs:
  
  Test:
    name: get semver
    runs-on: ubuntu-latest
    outputs:
      MODIFIED: ${{ steps.envvars.outputs.MODIFIED}}
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: get tag
      id: envvars
      run: |
        echo $SEMVER
        case ${GITHUB_REF} in 
          refs/tags/$SEMVER)
          echo "It's build from tag, yeah I see";;
        esac
        MODIFIED=$(date "+%Y-%m-%dT%H:%MZ")
        echo "{MODIFIED}={MODIFIED}" >> $GITHUB_OUTPUT

        
    
